# site
site_name: The BACK Stack
site_url: https://github.io/back-stack/backstack.dev
site_description: Platform Building made Easy

# repo
repo_name: back-stack
repo_url: https://github.com/back-stack/

# edit
edit_uri: backstack.dev/edit/main/docs/

# copyright
copyright: Made with ❤️ by The BACK stack contributors. Together, let's unlock the future of platform engineering.

# strictness
strict: true

# style
# Commented due to 404 errors, need to fix
# extra_css:
# - static/extra.css

# version
extra:
  version:
    provider: mike
  status:
    new: Recently added
    deprecated: Deprecated
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/back-stack/
    - icon: fontawesome/brands/slack
      link: https://cloud-native.slack.com/archives/C066BJRLS4B

theme:
  name: material
  custom_dir: docs/overrides
  language: en
  include_search_page: false
  search_index_only: true
  features:
    - announce.dismiss
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  palette:
  - media: "(prefers-color-scheme: light)" # Light mode
    scheme: default
    primary: light blue
    accent: light blue
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
  - media: "(prefers-color-scheme: dark)" # Dark mode
    scheme: slate
    primary: light blue
    accent: light blue
    toggle:
      icon: material/toggle-switch-off
      name: Switch to dark mode
  favicon: static/back-stack-favicon.png
  icon:
    logo: octicons/stack-24

plugins:
- search
- blog:
    enabled: true
    post_readtime: true
    blog_toc: true
    draft: false
- rss:
    enabled: !ENV [MKDOCS_ENABLE_RSS_PLUGIN, True]
    match_path: blog/posts/.*
    date_from_meta:
      as_creation: date
- minify:
    minify_html: true
- include-markdown
# - tags:
#     enabled: true
#     tags_file: catalog/index.md

markdown_extensions:
- attr_list
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- admonition
- codehilite
- footnotes
- meta
- toc:
    permalink: true
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.superfences
- pymdownx.tasklist:
    custom_checkbox: true

nav:
- Home: index.md
- Documentation:
    - intro.md
    - Quickstart: install.md
    - Architecture: arch.md
- News:
  - blog/index.md
