authors:
  boris:
    name: Boris Kurktchiev
    description: Chief Plumber
    avatar: https://avatars.githubusercontent.com/u/5804477?v=4
  ritesh:
    name: Ritesh Patel
    description: Founder Nirmata.com
    avatar: https://avatars.githubusercontent.com/u/3522560?v=4
